spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/silvalde_web_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:silvalde_web_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:silvalde_web_pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}
