spring.datasource.url=jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:silvalde_web_db}?allowPublicKeyRetrieval=true&useSSL=${MYSQL_USE_SSL:false}&requireSSL=${MYSQL_REQUIRE_SSL:false}&serverTimezone=UTC
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost}

logging.level.com.silvaldeweb=INFO
