spring.datasource.url=jdbc:mysql://localhost:3306/silvalde_web_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
app.cors.allowed-origin=http://localhost:5173

logging.level.org.springframework.security.access.intercept=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
